# Generated by Django 4.0.1 on 2022-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('auth', models.CharField(max_length=250)),
                ('https', models.CharField(max_length=250)),
                ('cors', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
